#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Color_region.Resource", IsApplication=true)]

namespace Color_region
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int camera_id = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int show_fps = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int ColorPickerButton = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int MyButton = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int PanelColorNoAlpha = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int any = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int back = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int color_picker_view = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int front = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int imageView1 = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int new_color_panel = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int old_color_panel = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_color_picker = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int button_color_picker_alpha = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int button_color_picker_noalpha = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int button_color_picker_round = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int dialog_color_picker = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int press_color_to_apply = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CameraBridgeViewBase = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int CameraBridgeViewBase_camera_id = 1;
			
			// aapt resource value: 0
			public const int CameraBridgeViewBase_show_fps = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
